import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative w-screen h-screen`}
        >
          <header className="bg-slate-900 text-white p-4 text-center">
            <Navigation />
          </header>

          <Providers>
            <main className="p-6">{children}</main>
          </Providers>

          <footer className="bg-slate-900 text-white p-4 text-center absolute bottom-0 w-full">
            Codevolution
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
